# Generated by Django 2.2 on 2020-02-18 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('applevel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=datetime.datetime(2020, 2, 18, 5, 41, 24, 849319, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
