# Generated by Django 2.2 on 2020-02-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applevel', '0004_auto_20200218_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
